name: secrets-and-variables.yml
on:
  workflow_dispatch:

jobs:
  configurar-app:
    runs-on: self-hosted

    steps:
      - name: Mostrar APP_MODE
        run: echo "Modo da aplicação ${{ vars.APP_MODE }}"

      - name: Enviar email de suporte (simulado)
        run: echo "Enviando email para ${{ vars.SUPPORT_EMAIL }}"

      - name: Autenticar com token de produção (simulado)
        run: echo "Autenticando com token sensível..."
        env:
          TOKEN: ${{ secrets.PROD_TOKEN }}

      - name: Verificar token está presente (mas não logar)
        run: |
          if [ -z "$TOKEN" ]; then
            echo "Token não fornecido!"
            exit 1
          else
            echo "Token recebido com sucesso (oculto)"
          fi
        env:
          TOKEN: ${{ secrets.PROD_TOKEN }}