name: Runner Local Ubuntu-WSL

on:
  workflow_dispatch:

jobs:
  testar-runner-local:
    runs-on: self-hosted
    steps:
      - name: Mostrar informações do sistema
        run: uname -a

      - name: Atualizar pacotes e instalar Java/Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk maven

      - name: Mostrar versão do Java
        run: java -version || echo "Java não instalado"